import { Spot } from "./types";

export const FALLBACK_SPOTS: Spot[] = [
  // --- SAN FRANCISCO ---
  {
    id: "spot-sf-1",
    name: "The Conservatory Room",
    category: "Botanical Plant Cafe",
    city: "San Francisco",
    priceLevel: "$$",
    priceUsd: 14,
    vibeTags: ["plantparadise", "sagegreen", "wabisabi", "warmgoldenhour"],
    description: "Sun-lit industrial glass atrium overflowing with rare monsteras and raw travertine surfaces. Ideal for solo journaling and listening to low-key jazz.",
    location: "Soma District • SF",
    lighting: "Warm Skylight Glow",
    noise: "Calm Whisper (Lo-Fi Jazz)",
    seating: "Velvet Loveseats & Teak Desks",
    instagramHandle: "conservatoryroom",
    coVibersCount: 8,
    savedCount: 245,
    rating: "98% Cozy",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Kyoto Whisked Matcha", "Lavender Honey Latte", "Rosemary Sea Salt Croissant"],
    placeLayout: "Double glass greenhouse with gravel paths and high ceilings",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Trending Hotspot (24k mentions)",
    lat: 37.7749,
    lng: -122.4194,
    explorerMode: "local"
  },
  {
    id: "spot-sf-2",
    name: "Sutro Coastal Glasshouse",
    category: "Coastal Public Park & Solarium",
    city: "San Francisco",
    priceLevel: "$",
    priceUsd: 0,
    vibeTags: ["plantparadise", "sagegreen", "warmgoldenhour"],
    description: "Perched high over Lands End, this historic glass solarium looks upon sunset shorelines. Coastal pines, whispering fog, and peaceful stone architecture.",
    location: "Lands End • SF",
    lighting: "Vaporous Marine Sunsets",
    noise: "Sighing Pine Trees & Ocean Swell",
    seating: "Weathered Cedar Slabs",
    instagramHandle: "sutro_glasshouse",
    coVibersCount: 15,
    savedCount: 520,
    rating: "99% Breathtaking",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Artisanal Wildberry Infusions", "Seaside Shortbread Biscuit"],
    placeLayout: "Victorian steel framework wrapping around a winding spiral of native succulents",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Classic Lookout (38k mentions)",
    lat: 37.7801,
    lng: -122.5119,
    explorerMode: "visitor"
  },

  // --- SEATTLE ---
  {
    id: "spot-sea-1",
    name: "The Cedar Room & Brew",
    category: "Botanical Plant Cafe",
    city: "Seattle",
    priceLevel: "$$",
    priceUsd: 11,
    vibeTags: ["plantparadise", "sagegreen", "wabisabi"],
    description: "Surrounded by deep PNW ferns and rustic cedar logs. Towering skylights turn overcast rainy afternoons into soft, therapeutic pools of amber light.",
    location: "Capitol Hill • Seattle",
    lighting: "Diffused Overcast Softness",
    noise: "Mellow Indie Acoustic Loops",
    seating: "Hewn Alderwood Benches",
    instagramHandle: "cedar_room_seattle",
    coVibersCount: 12,
    savedCount: 340,
    rating: "97% Cozy",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Maple Alderwood Latte", "Spiced Sage Butter Scone"],
    placeLayout: "Timber-framed cabin with dense hanging air plants and cozy fire stove",
    yelpRating: 4.7,
    googleRating: 4.9,
    instagramActivity: "Local Secret (11k mentions)",
    lat: 47.6154,
    lng: -122.3215,
    explorerMode: "local"
  },
  {
    id: "spot-sea-2",
    name: "Puget Sound Glass Canopy",
    category: "Waterfront Conservatory & Pier",
    city: "Seattle",
    priceLevel: "$$",
    priceUsd: 18,
    vibeTags: ["neutraltones", "minimalist", "cleanlines"],
    description: "An astronomical glass pavilion hosting massive floating modern steel structures. Perfect for watching ferry ships drift by in the misty salt-scented air.",
    location: "Elliott Bay Waterfront • Seattle",
    lighting: "Moody Grey Sea-glare & Steel Reflection",
    noise: "Echoing Ferry Horns & Soft Wind",
    seating: "Sleek Granite Plinths",
    instagramHandle: "pugetcanopy",
    coVibersCount: 22,
    savedCount: 680,
    rating: "98% Panoramic",
    image: "https://images.unsplash.com/photo-1463936575829-25148e1db1b8?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Smoked Alder Salmon Filet Toast", "Huckleberry Espresso Macchiato"],
    placeLayout: "Architectural zigzag steel paths descending directly to Seattle's saltwater shore",
    yelpRating: 4.9,
    googleRating: 4.8,
    instagramActivity: "Stellar Ocean Hub (41k mentions)",
    lat: 47.6163,
    lng: -122.3533,
    explorerMode: "visitor"
  },

  // --- NEW YORK ---
  {
    id: "spot-ny-1",
    name: "The Archival Library",
    category: "Hidden Book Sanctuary",
    city: "New York",
    priceLevel: "$$",
    priceUsd: 12,
    vibeTags: ["cozybooths", "candlelit", "vintage"],
    description: "Warm, rich timber walls lined with antique leather-bound chronicles. Lit softly by a collection of vintage banker lamps for deep, intimate study sessions.",
    location: "Greenwich Village • NYC",
    lighting: "Flickering Amber Bulb & Green Glass Lamps",
    noise: "Soft Static Rain Noise & Soft Pages",
    seating: "Buttoned Wine-Red Leather Wingbacks",
    instagramHandle: "ny_archival_sanctuary",
    coVibersCount: 18,
    savedCount: 890,
    rating: "98% Studious",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Single-Origin Filter Brew", "Cardamom Orange Scone"],
    placeLayout: "Two stories of heavy cedar drawers, green felt desks, and dusty paper aromas",
    yelpRating: 4.9,
    googleRating: 4.8,
    instagramActivity: "Academic Sanctuary (31k mentions)",
    lat: 40.7308,
    lng: -73.9973,
    explorerMode: "local"
  },
  {
    id: "spot-ny-2",
    name: "Maison Pothos Atrium",
    category: "Vertical Glasshouse Garden",
    city: "New York",
    priceLevel: "$$$",
    priceUsd: 24,
    vibeTags: ["plantparadise", "sagegreen", "warmgoldenhour"],
    description: "A breathtaking three-story sky conservatory inside SoHo. Massive steel arches suspend dripping ivy and cascading pothos creepers high over stone floors.",
    location: "SoHo District • NYC",
    lighting: "Intense Overhead Golden Hour Glass",
    noise: "Grateful Piano Melodies & Water Dripping",
    seating: "Woven Wicker Lounge Chairs",
    instagramHandle: "maison_pothos_nyc",
    coVibersCount: 30,
    savedCount: 1250,
    rating: "99% Sublime",
    image: "https://images.unsplash.com/photo-1463936575829-25148e1db1b8?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Wild Rose Ceremonial Matcha", "Pistachio Custard Crois-tart"],
    placeLayout: "Soaring vertical glass atrium with spiral timber steps and lush plant tiers",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Atrium Legend (62k mentions)",
    lat: 40.7233,
    lng: -74.0030,
    explorerMode: "visitor"
  },

  // --- HO CHI MINH CITY ---
  {
    id: "spot-hcmc-1",
    name: "Silent Cassette Cafe",
    category: "Hidden Alley Tea Room",
    city: "Ho Chi Minh City",
    priceLevel: "$",
    priceUsd: 4,
    vibeTags: ["wabisabi", "candlelit", "neutraltones"],
    description: "A quiet refuge nestled deep within a shaded alleyway. Time stands still beside vintage cassette players, accompanied by rustic wooden furniture and sweet lotus tea.",
    location: "Nguyen Dinh Chieu Alley • District 3 • HCMC",
    lighting: "Muffled Candlelight & Warm Vintage Table Lamps",
    noise: "Soft Analog Cassette Tapes & Whispering Rainfalls",
    seating: "Low Oak Lounge Chairs & Raw Linen Cushions",
    instagramHandle: "lang_cassette",
    coVibersCount: 14,
    savedCount: 390,
    rating: "98% Poetic",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Ginseng Lotus Cold Brew Tea", "Creamy Saigon Salted Coffee", "Artisanal Jasmine Butter Cookies"],
    placeLayout: "A simple wooden hideout with time-weathered book racks and a classic 80s vinyl turntable",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Quiet Vault (14k bookmarks)",
    lat: 10.7765,
    lng: 106.6853,
    explorerMode: "local"
  },
  {
    id: "spot-hcmc-2",
    name: "Botanical Zoo Glasshouse",
    category: "Historic Botanical Conservatory",
    city: "Ho Chi Minh City",
    priceLevel: "$",
    priceUsd: 2,
    vibeTags: ["plantparadise", "sagegreen", "wabisabi"],
    description: "A historic French colonial conservatory with beautiful iron-vaulted trusses in the heart of Saigon's botanical gardens. Sunlight streams through dense tropical palms.",
    location: "Nguyen Binh Khiêm St • District 1 • HCMC",
    lighting: "Vibrant Tropical Sunbeams Filtering Through Glass",
    noise: "Singing Forest Birds & Whispering Banyan Trees",
    seating: "Weathered Iron Garden Bench & Outdoor Tables",
    instagramHandle: "thaocamvien_glasshouse",
    coVibersCount: 25,
    savedCount: 820,
    rating: "96% Immersive",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Fresh Honey Passionfruit Nectar", "Saigon Coconut Frappe Latte"],
    placeLayout: "A 19th-century patterned steel glasshouse gathering rare orchids and towering wild ferns",
    yelpRating: 4.7,
    googleRating: 4.8,
    instagramActivity: "Saigon Nostalgia (48k mentions)",
    lat: 10.7875,
    lng: 106.7051,
    explorerMode: "visitor"
  },

  // --- TOKYO ---
  {
    id: "spot-tokyo-1",
    name: "Komorebi Yanaka Chashitsu",
    category: "Hidden Tea Sanctuary",
    city: "Tokyo",
    priceLevel: "$$",
    priceUsd: 12,
    vibeTags: ["wabisabi", "neutraltones", "minimalist"],
    description: "Tucked behind a wooden temple fence in Yanaka, this tea counter focuses on quietude. Dappled sunlight filters through maple leaves directly onto handmade gray clay tea bowls.",
    location: "Yanaka Backstreets • Tokyo",
    lighting: "Komorebi (Dappled Tree Light)",
    noise: "Soft Whistle of Boiling Cast-Iron Kettle",
    seating: "Woven Tatami Mats & Raw Elm Desk",
    instagramHandle: "komorebi_yanaka",
    coVibersCount: 9,
    savedCount: 430,
    rating: "99% Zen",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Uji Matcha with Hand-ground Foam", "Wagashi Sugared Raindrop Cake"],
    placeLayout: "A five-seat raw cedar counter overlooking a tiny mossy raked-gravel courtyard",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Local Haven (8k mentions)",
    lat: 35.7262,
    lng: 139.7686,
    explorerMode: "local"
  },
  {
    id: "spot-tokyo-2",
    name: "Sumida Aqua-Forest Glasshouse",
    category: "Architectural Aquarium & Observatory",
    city: "Tokyo",
    priceLevel: "$$$",
    priceUsd: 26,
    vibeTags: ["minimalist", "cleanlines", "brutalistmono"],
    description: "An extraordinary modern architectural park containing grand glowing jellyfish glass silos. Minimalist concrete slabs rise like towers over luminescent, quiet streams.",
    location: "Oshiage • Tokyo",
    lighting: "Bioluminescent Pale Blue & Indigo Glow",
    noise: "Gentle Bubbling Streams & Ambient Synths",
    seating: "Sculptive Matte Granite Steps",
    instagramHandle: "sumida_aqua_forest",
    coVibersCount: 38,
    savedCount: 1540,
    rating: "98% Majestic & Mystic",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Blue-Ocean Matcha Soda with Soda Jelly Plop", "Charcoal Baked Squid Pie"],
    placeLayout: "Basalt slabs, giant glowing glass columns, and a cascading artificial river layout",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Sci-Fi Oasis (95k mentions)",
    lat: 35.7101,
    lng: 139.8107,
    explorerMode: "visitor"
  },

  // --- SEOUL ---
  {
    id: "spot-seoul-1",
    name: "Samyang Hanok Bibliophile",
    category: "Hanok Book & Tea Vault",
    city: "Seoul",
    priceLevel: "$$",
    priceUsd: 10,
    vibeTags: ["vintage", "wabisabi", "cozybooths"],
    description: "A private, secluded hanok library hidden in Samcheong-dong. Floor-to-ceiling wooden scrolls, low tables, and dense collections of indie literature create an absolute retreat.",
    location: "Samcheong-dong Lane • Seoul",
    lighting: "Warm Incandescent Glow Over Hanji Paper",
    noise: "Quiet Rain Soundscape playing from vintage speakers",
    seating: "Linen Cushions on Heated Pine Floors",
    instagramHandle: "samyang_hanok",
    coVibersCount: 11,
    savedCount: 310,
    rating: "97% Cozy",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Sujungwa Amber Persimmon Tea", "Roasted Rice cake with Lavender Honey"],
    placeLayout: "Renovated central-courtyard hanok with exposed rafters and private desk niches",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Curated Hideout (12k mentions)",
    lat: 37.5812,
    lng: 126.9818,
    explorerMode: "local"
  },
  {
    id: "spot-seoul-2",
    name: "Dongdaemun Silver Oasis Garden",
    category: "Futuristic Canopy Park & Landmark",
    city: "Seoul",
    priceLevel: "$",
    priceUsd: 0,
    vibeTags: ["minimalist", "cleanlines", "brutalistmono"],
    description: "A spectacular, epic silver stadium wrapped in thousands of shimmering metallic panels. At night, a silent lawn of white fiber-optic roses glows to create a dreamy, sci-fi landscape.",
    location: "Dongdaemun Place • Seoul",
    lighting: "Cybernetic Silver Neon & Moonlight",
    noise: "Hum of Night city winds & distant murmur",
    seating: "Poured-concrete Curving Slopes",
    instagramHandle: "dongdaemun_oasis",
    coVibersCount: 45,
    savedCount: 2200,
    rating: "99% Epic",
    image: "https://images.unsplash.com/photo-1555543966-6d6986181090?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Matcha Charcoal Softserve (At nearby kiosk)", "Cold-pressed Plum Shaved Ice"],
    placeLayout: "Massive concrete arches and flowing steel planes that seamless warp from floor to ceiling",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Global Wonder (150k mentions)",
    lat: 37.5665,
    lng: 127.0092,
    explorerMode: "visitor"
  },

  // --- LONDON ---
  {
    id: "spot-london-1",
    name: "The Bloomsbury Ivy Parlour",
    category: "Hidden Reading Parlour & Tea",
    city: "London",
    priceLevel: "$$",
    priceUsd: 16,
    vibeTags: ["vintage", "cozybooths", "candlelit"],
    description: "An ivy-shrouded tea parlour tucked behind Bloomsbury square. Brass bookstands, ticking vintage grandfather clocks, and dense antique smell make it absolute heaven.",
    location: "Bloomsbury lane • London",
    lighting: "Soft flickering green/gold lamp shadow",
    noise: "Distant chime of clock & rain on window frame",
    seating: "Spacious Green Velvet Chesterfield Couches",
    instagramHandle: "bloomsbury_parlour",
    coVibersCount: 8,
    savedCount: 410,
    rating: "98% Cozy & Literary",
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["English Rose Blend with Lavender Honey", "Warm Scone with Clotted Cream"],
    placeLayout: "Charming Victorian basement library with brick fireplace and stacks of old poetry books",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Secret Spot (15k mentions)",
    lat: 51.5200,
    lng: -0.1240,
    explorerMode: "local"
  },
  {
    id: "spot-london-2",
    name: "Kew temperate Glass Palace",
    category: "Grand Royal Botanic Conservatory",
    city: "London",
    priceLevel: "$$$",
    priceUsd: 22,
    vibeTags: ["plantparadise", "sagegreen", "cleanlines"],
    description: "The world's largest Victorian glasshouse. An awe-inspiring white cast-iron structure protecting ancient cloud-forest tree ferns and endangered botanical wonders.",
    location: "Kew Gardens • Richmond • London",
    lighting: "Cathedral-scale daylight through massive arches",
    noise: "Distant tropical waterfall splash & birdsong echo",
    seating: "Ornate White Wrought-iron Benches",
    instagramHandle: "kew_temperate_palace",
    coVibersCount: 30,
    savedCount: 1890,
    rating: "99% Majestic",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Organic Matcha & Pistachio Tartat", "Cold Whisked Elderflower cordial"],
    placeLayout: "Vast double-height Victorian white steel glass framework with winding aerial skywalks",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Global Royal Landmark (210k mentions)",
    lat: 51.4791,
    lng: -0.2934,
    explorerMode: "visitor"
  },

  // --- PARIS ---
  {
    id: "spot-paris-1",
    name: "Arcade Vinyl & Books",
    category: "Secret Arcade Reading Salon",
    city: "Paris",
    priceLevel: "$$",
    priceUsd: 14,
    vibeTags: ["vintage", "wabisabi", "candlelit"],
    description: "Hidden within the wooden hallways of the Passage des Panoramas. Combines retro analog vinyl records with rare poetry books on sepia paper.",
    location: "Passage des Panoramas • Paris",
    lighting: "Warm golden lights from the historic glass passage roof",
    noise: "Quiet turntable static (Curated French Chanson vinyl)",
    seating: "Plush leather low chairs & small marble tables",
    instagramHandle: "passage_vinyl_paris",
    coVibersCount: 6,
    savedCount: 290,
    rating: "96% Poetic",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Cedar-smoked Espresso Tonic", "Classic Matcha Pain au Chocolat"],
    placeLayout: "Charming historic glass-roof booth lined with wood shelves and framed retro art prints",
    yelpRating: 4.7,
    googleRating: 4.8,
    instagramActivity: "Underground Gem (10k mentions)",
    lat: 48.8712,
    lng: 2.3418,
    explorerMode: "local"
  },
  {
    id: "spot-paris-2",
    name: "Musée de l'Orangerie Water Lily Court",
    category: "Architectural Museum Gallery",
    city: "Paris",
    priceLevel: "$$",
    priceUsd: 15,
    vibeTags: ["minimalist", "neutraltones", "cleanlines"],
    description: "A spectacular, oval-shaped white room built in absolute minimalist style to host Monet's giant Water Lilies paintings. A spiritual sanctuary in Paris.",
    location: "Jardin des Tuileries • Paris",
    lighting: "Pure Diffused Skylight through frosted oval ceiling",
    noise: "Complete Silent reverie (Hushed footsteps)",
    seating: "Vast white curved central benches",
    instagramHandle: "orangerie_sanctuary",
    coVibersCount: 20,
    savedCount: 1980,
    rating: "99% Sublime",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Scented organic tea (At the gallery cafe)", "Pistachio macaron gateau"],
    placeLayout: "Two seamless oval galleries mirroring the curve of the infinite water lily canvases",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Legendary Sanctuary (130k mentions)",
    lat: 48.8638,
    lng: 2.3226,
    explorerMode: "visitor"
  },

  // --- TAMPA ---
  {
    id: "spot-tampa-1",
    name: "Banyan Shade Brews",
    category: "Hidden Courtyard Cafe",
    city: "Tampa",
    priceLevel: "$$",
    priceUsd: 8,
    vibeTags: ["plantparadise", "sagegreen", "wabisabi"],
    description: "An incredibly quiet, shady garden courtyard hidden away in Tampa's brick-paved lanes. Overhung by spectacular century-old Banyan branches and trailing ferns.",
    location: "Historic Ybor City • Tampa",
    lighting: "Warm tropical canopy dappled shades",
    noise: "Quiet acoustic guitar and trickling rock pool fountain",
    seating: "Wrought-iron bistro chairs and vine-covered stone blocks",
    instagramHandle: "banyanshade_tampa",
    coVibersCount: 7,
    savedCount: 195,
    rating: "95% Cozy Lush",
    image: "https://images.unsplash.com/photo-1463936575829-25148e1db1b8?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Organic Iced Matcha Coconut Shake", "Guava Cream Cheese Puff Bun"],
    placeLayout: "Secret interior Spanish courtyard tiled with terracotta terracotta clay patterns",
    yelpRating: 4.7,
    googleRating: 4.8,
    instagramActivity: "Local Haven (8k mentions)",
    lat: 27.9628,
    lng: -82.4452,
    explorerMode: "local"
  },
  {
    id: "spot-tampa-2",
    name: "The Underwater Coral Dome",
    category: "Grand Ocean Aquarium & Reef",
    city: "Tampa",
    priceLevel: "$$$",
    priceUsd: 32,
    vibeTags: ["minimalist", "cleanlines", "brutalistmono"],
    description: "An awe-inspiring, massive half-circle glass dome showcasing a dramatic underwater coral reef wall. Giant sea creatures sweep silently overhead inside the dim blue abyss.",
    location: "Channel District Wharf • Tampa",
    lighting: "Ethereal Aqua Marine Blue Shimmer",
    noise: "Muffled water rumbles & soft orchestra vibes",
    seating: "Expansive curved carpeted viewing gallery steps",
    instagramHandle: "tampacoralreef",
    coVibersCount: 22,
    savedCount: 940,
    rating: "98% Majestic",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Blueberry mint tea shaker", "Sea salt roasted cookies"],
    placeLayout: "Subterranean tunnel made of huge glass arcs directly joining the underwater sea garden",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Water Magic (52k mentions)",
    lat: 27.9442,
    lng: -82.4449,
    explorerMode: "visitor"
  },

  // --- ORLANDO ---
  {
    id: "spot-orlando-1",
    name: "The Fernery Matcha Lounge",
    category: "Hidden Garden Library",
    city: "Orlando",
    priceLevel: "$$",
    priceUsd: 11,
    vibeTags: ["sagegreen", "plantparadise", "cozybooths"],
    description: "A gorgeous, private green sanctuary hidden away in Orlando's outer garden lanes. Surrounded by hanging ferns, climbing vines, and rows of botanical design books.",
    location: "Winter Park Garden Lane • Orlando",
    lighting: "Warm incandescent bulbs under large wicker covers",
    noise: "Quiet organic bird track and rain sounds",
    seating: "Oversized linen-upholstered couches and study nooks",
    instagramHandle: "fernery_orlando",
    coVibersCount: 9,
    savedCount: 215,
    rating: "97% Relaxing",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Matcha with Almond Foam", "Cardamom Honey cake piece"],
    placeLayout: "Charming cottage-style stone room leading to a garden glass greenhouse patio",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Hidden Gem (9k mentions)",
    lat: 28.5996,
    lng: -81.3392,
    explorerMode: "local"
  },
  {
    id: "spot-orlando-2",
    name: "Wekiwa Blue Springs Lagoon",
    category: "Natural Spring Lagoon Park",
    city: "Orlando",
    priceLevel: "$",
    priceUsd: 6,
    vibeTags: ["plantparadise", "warmgoldenhour"],
    description: "An unbelievable natural spring basin. Crystal-clear turquoise water kept at 72 degrees year-round, surrounded by towering cypress trees and ancient mosses.",
    location: "Wekiwa Basin Preserve • Orlando",
    lighting: "Brilliant tropical canopy daylight & gold sunsets",
    noise: "Gentle bubbling water spring & soft forest leaves rustle",
    seating: "Raw cedar wood log benches & grassy slopes",
    instagramHandle: "wekiwa_blue_lagoon",
    coVibersCount: 28,
    savedCount: 1100,
    rating: "99% Aventurous & Pure",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Açai Berry Shaker", "Cold Lemon-infused ginger tea"],
    placeLayout: "Vast natural spring basin bordered by white sandy shores and ancient cypress tree docks",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Nature Miracle (72k mentions)",
    lat: 28.7118,
    lng: -81.4604,
    explorerMode: "visitor"
  },

  // --- CHICAGO ---
  {
    id: "spot-chicago-1",
    name: "The Basalt & Bean Vault",
    category: "Subterranean Coffee Vault",
    city: "Chicago",
    priceLevel: "$$",
    priceUsd: 11,
    vibeTags: ["brutalistmono", "neutraltones", "minimalist"],
    description: "Deep underground in Chicago's Loop, this concrete coffee vault is absolute peace. Textured basalt stone lines the space with zero echo. Incredible espresso craftsmanship.",
    location: "The Loop Vaults • Chicago",
    lighting: "Low copper spotlights and glowing stone counter edge",
    noise: "Quiet hum of espresso machines & soft ambient synth tracks",
    seating: "Molded heavy sandstone slab benches",
    instagramHandle: "basaltbean_chicago",
    coVibersCount: 8,
    savedCount: 310,
    rating: "96% Meditative",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Charcoal Honey Roast Espresso", "Salted Butter Matcha Sourdough Toast"],
    placeLayout: "Heavy concrete geometric sanctuary with massive slate stone columns",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Secret Coffee Vault (18k mentions)",
    lat: 41.8781,
    lng: -87.6298,
    explorerMode: "local"
  },
  {
    id: "spot-chicago-2",
    name: "Shedd Glass Reef Rotunda",
    category: "Grand Ocean Conservatory",
    city: "Chicago",
    priceLevel: "$$$",
    priceUsd: 38,
    vibeTags: ["minimalist", "cleanlines"],
    description: "A spectacular Beaux-Arts octagonal rotunda looking right over Lake Michigan. Enormously tall glass panes enclose glowing aquatic reef silos filled with thousands of exotic fishes.",
    location: "Museum Campus Wharf • Chicago",
    lighting: "Grand central skylight & glowing underwater cyan hue",
    noise: "Gentle cascading water sound & quiet reverb",
    seating: "Large circular marble benches",
    instagramHandle: "sheddreof",
    coVibersCount: 35,
    savedCount: 2200,
    rating: "98% Breathtaking",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Lavender Sea-salt Soda", "Kyoto Whipped Matcha Frappé"],
    placeLayout: "Octagonal classical marble hall enclosing a giant central 360-degree marine column tank",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Water Masterpiece (140k mentions)",
    lat: 41.8676,
    lng: -87.6140,
    explorerMode: "visitor"
  },

  // --- ATLANTA ---
  {
    id: "spot-atlanta-1",
    name: "Cabbagetown Greenery & Espresso",
    category: "Hidden Plant & Matcha Hub",
    city: "Atlanta",
    priceLevel: "$$",
    priceUsd: 10,
    vibeTags: ["sagegreen", "plantparadise", "wabisabi"],
    description: "A magical plant studio and tea house inside a brick mill loft. Towering ferns and hanging climbing ivy make it Atlanta's quietest spot for creative thinkers.",
    location: "Cabbagetown Mill District • Atlanta",
    lighting: "Soft warm industrial window daylight",
    noise: "Gentle lo-fi folk music on vintage speakers",
    seating: "Reclaimed timber tables and single cozy armchairs",
    instagramHandle: "cabbagetown_matcha",
    coVibersCount: 10,
    savedCount: 240,
    rating: "97% Green Sanctuary",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Spiced Mint Matcha Tea", "Cardamom Peach Pastry Slice"],
    placeLayout: "High ceiling brick-walled warehouse filled with plant propagation tiers and wooden workbenches",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Local Haven (12k mentions)",
    lat: 33.7486,
    lng: -84.3643,
    explorerMode: "local"
  },
  {
    id: "spot-atlanta-2",
    name: "Georgia Ocean Conservatory Dome",
    category: "Grand Ocean Aquarium & Dome",
    city: "Atlanta",
    priceLevel: "$$$",
    priceUsd: 42,
    vibeTags: ["minimalist", "cleanlines", "brutalistmono"],
    description: "An unbelievable, mountain-scale marine observatory showcasing giant whale sharks. A monumental glass window wraps around you in a cathedral of glowing deep blue oceanic light.",
    location: "Downtown Park Plaza • Atlanta",
    lighting: "Cascading mystical blue depths shine",
    noise: "Soft ocean depths rumble & symphonic cello waves",
    seating: "Vast carpeted theater viewing steps",
    instagramHandle: "ga_ocean_canopy",
    coVibersCount: 42,
    savedCount: 2900,
    rating: "99% Majestic Scale",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Matcha Sea Foam Shaker", "Blueberry Almond Pie Cake"],
    placeLayout: "Colossal viewing auditorium enclosing a 6-million-gallon marine habitat",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Epic Wonder (180k mentions)",
    lat: 33.7625,
    lng: -84.3942,
    explorerMode: "visitor"
  },

  // --- WASHINGTON D.C. ---
  {
    id: "spot-dc-1",
    name: "The Georgetown Ivy Study",
    category: "Secluded Courtyard Cafe",
    city: "Washington D.C.",
    priceLevel: "$$",
    priceUsd: 13,
    vibeTags: ["cozybooths", "vintage", "candlelit"],
    description: "An elegant, brick-walled courtyard study hidden behind an ivy-covered Georgetown cottage. Filled with shelves of history records and quiet, dim corners.",
    location: "Georgetown Lanes • Washington D.C.",
    lighting: "Soft warm yellow fire sparks & low glass lamps",
    noise: "Quiet crackling cedar fire hearth & hushed talk",
    seating: "Deep leather study desks and vintage armchairs",
    instagramHandle: "georgetown_ivy_study",
    coVibersCount: 9,
    savedCount: 380,
    rating: "98% Secret & Elegant",
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Honey Lavender Flat White", "Cinnamon Roasted Pear Bun"],
    placeLayout: "Charming multi-room townhouse library with a fireplace and old flag prints",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Local Secret (14k mentions)",
    lat: 38.9072,
    lng: -77.0628,
    explorerMode: "local"
  },
  {
    id: "spot-dc-2",
    name: "Smithsonian Conservatory Solarium",
    category: "Grand Glass Solarium & Museum",
    city: "Washington D.C.",
    priceLevel: "$",
    priceUsd: 0,
    vibeTags: ["plantparadise", "sagegreen", "minimalist"],
    description: "An awe-inspiring, Victorian cast-iron glass monument nestled on the National Mall. Filled with hundreds of lush tropical orchids and ancient palms reaching towards sky-high steel vaults.",
    location: "National Mall Solarium • Washington D.C.",
    lighting: "Warm tropical glasshouse glow through arched panes",
    noise: "Soft rain mists & echoing birds",
    seating: "Ornate dark cast-iron decorative benches",
    instagramHandle: "smithsonian_orchid_dome",
    coVibersCount: 32,
    savedCount: 1620,
    rating: "99% Sublime Preservation",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Iced Jasmine Green Tea Shaker", "Salted Vanilla Biscuit"],
    placeLayout: "Ornate glass conservatory built in 1842 with giant central iron dome and spiral stairs",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Solarium Beauty (98k mentions)",
    lat: 38.8884,
    lng: -77.0125,
    explorerMode: "visitor"
  },

  // --- BOSTON ---
  {
    id: "spot-boston-1",
    name: "Beacon Hill Antique Study",
    category: "Historic Books & Espresso Cafe",
    city: "Boston",
    priceLevel: "$$",
    priceUsd: 12,
    vibeTags: ["vintage", "cozybooths", "candlelit"],
    description: "Tucked inside an 1800s brick brownstone in Beacon Hill. Wooden bookcases enclose old vintage leather books, leather study desks, and quiet classical tunes.",
    location: "Charles Street Corner • Boston",
    lighting: "Cozy flickering brass green banker lamps",
    noise: "Quiet violin loops & slow ticking grandfather clock",
    seating: "Plush leather wingback armchairs & private study desks",
    instagramHandle: "beaconhill_antique_study",
    coVibersCount: 11,
    savedCount: 420,
    rating: "97% Scholarly Room",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Boston Cream Roast Espresso", "Cardamom infused Sea-salt bun"],
    placeLayout: "Charming historic library room with custom dark oak woodwork",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Underground Gem (12k mentions)",
    lat: 42.3588,
    lng: -71.0707,
    explorerMode: "local"
  },
  {
    id: "spot-boston-2",
    name: "Isabella Venetian Court Gallery",
    category: "Grand Museum Garden Courtyard",
    city: "Boston",
    priceLevel: "$$",
    priceUsd: 20,
    vibeTags: ["plantparadise", "sagegreen", "wabisabi"],
    description: "An absolutely stunning four-story Venetian-style courtyard garden inside a historic museum. Lit of skylights, showcasing ancient marble structures and deep orange orchids.",
    location: "Fenway Palace Lane • Boston",
    lighting: "Overhead sky glass warmth highlighting marble arches",
    noise: "Symphony of stone fountain water ripples",
    seating: "Sculptive Roman limestone steps",
    instagramHandle: "isabellapalace_court",
    coVibersCount: 29,
    savedCount: 2400,
    rating: "99% Architectural Masterwork",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Organic Rose Buds Whisked Matcha", "Pistachio Almond Tartlet"],
    placeLayout: "Four-story enclosed interior Roman court decorated with moss gardens and marble columns",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Stellar Garden Center (160k mentions)",
    lat: 42.3384,
    lng: -71.0991,
    explorerMode: "visitor"
  },

  // --- HOUSTON ---
  {
    id: "spot-houston-1",
    name: "Subterranean Water Cistern",
    category: "Subterranean Echo Chamber & Echo Cafe",
    city: "Houston",
    priceLevel: "$$",
    priceUsd: 10,
    vibeTags: ["brutalistmono", "neutraltones", "minimalist"],
    description: "A spectacular masterwork hidden underground. An enormous concrete water monument with hundreds of massive pillars, glowing with changing amber light and beautiful acoustic echoes.",
    location: "Buffalo Bayou Park • Houston",
    lighting: "Ethereal low-key golden spotlights and shadow lines",
    noise: "Hypnotic seventeen-second sound echo & quiet ambient tune",
    seating: "Polished raw basalt blocks",
    instagramHandle: "bayou_cistern_hbx",
    coVibersCount: 7,
    savedCount: 520,
    rating: "98% Meditative Depth",
    image: "https://images.unsplash.com/photo-1555543966-6d6986181090?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Chai Cardamom Cold Brew", "Mocha Chocolate Chunk Cake"],
    placeLayout: "Vast subterranean architectural concrete vault built in 1926",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Underground Magic (28k mentions)",
    lat: 29.7619,
    lng: -95.3853,
    explorerMode: "local"
  },
  {
    id: "spot-houston-2",
    name: "The Rainforest Bio-Dome",
    category: "Grand Conservatory & Butterfly Garden",
    city: "Houston",
    priceLevel: "$$",
    priceUsd: 14,
    vibeTags: ["plantparadise", "sagegreen", "cleanlines"],
    description: "An incredible three-story cone-shaped glass bio-dome. Experience a lush tropical rainforest, complete with a massive vertical waterfall and thousands of flying butterflies.",
    location: "Museum of Natural Science • Houston",
    lighting: "Intense tropical sky glass & mist reflections",
    noise: "Crackling waterfall rumble & wind in palm branches",
    seating: "Curved hardwood garden benches",
    instagramHandle: "rainforest_biodome",
    coVibersCount: 32,
    savedCount: 1650,
    rating: "99% Immersive Wilderness",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Pressed Mango Mint Shaker", "Cold Matcha Lavender Tonic"],
    placeLayout: "Three-story curvilinear glass dome wrapping around a towering vertical jungle centerpiece",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Tropical Haven (92k mentions)",
    lat: 29.7222,
    lng: -95.3898,
    explorerMode: "visitor"
  },

  // --- AUSTIN ---
  {
    id: "spot-austin-1",
    name: "Deep Eddy Vinyl & Cafe",
    category: "Hidden Record Vinyl Cafe",
    city: "Austin",
    priceLevel: "$$",
    priceUsd: 9,
    vibeTags: ["vinylonly", "wabisabi", "cozybooths"],
    description: "A gorgeous, private study lounge hidden in Austin's old tree corners. Sip single-origin pour-overs in secluded amber booths while listening to historic indie rock vinyls.",
    location: "Deep Eddy Corner • Austin",
    lighting: "Warm low-key vintage incandescent gold shine",
    noise: "Warm record scratch sound (Indie Rock & Folk)",
    seating: "Low-slung leather chairs and red cedar study counters",
    instagramHandle: "deepeddy_vinyl",
    coVibersCount: 12,
    savedCount: 290,
    rating: "96% Cool & Independent",
    image: "https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Cedar-smoked Honey Pour-over", "Pecan Cinnamon bun slice"],
    placeLayout: "Basement timber record booth lined with vintage posters and a giant fireplace",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Local Hideaway (9k mentions)",
    lat: 30.2790,
    lng: -97.7725,
    explorerMode: "local"
  },
  {
    id: "spot-austin-2",
    name: "Barton Springs Natural Spring Lagoon",
    category: "Natural Spring-Fed Quarry Lagoon",
    city: "Austin",
    priceLevel: "$",
    priceUsd: 5,
    vibeTags: ["sagegreen", "plantparadise", "warmgoldenhour"],
    description: "An incredible natural swimming lagoon inside Zilker park. Spring-fed pool of 68 degrees, shaded by colossal pecan trees, offering an absolute poetry and adventure escape.",
    location: "Zilker Park Preserve • Austin",
    lighting: "Warm golden sky glare over water waves",
    noise: "Laughing water waves and breeze in ancient trees",
    seating: "Vast grassy hill slopes and limestone block rails",
    instagramHandle: "barton_springs_lagoon",
    coVibersCount: 40,
    savedCount: 3100,
    rating: "99% Pure Oasis",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Cherry Hibiscus Shaker Blend", "Fresh lime coconut water glass"],
    placeLayout: "Monumental natural spring pool fed directly by limestone deep underground fountains",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Austin Icon (180k mentions)",
    lat: 30.2638,
    lng: -97.7712,
    explorerMode: "visitor"
  },

  // --- HANOI ---
  {
    id: "spot-hanoi-1",
    name: "Yen Cafe • Do Quang Alley",
    category: "Hidden Alley Cafe",
    city: "Hanoi",
    priceLevel: "$",
    priceUsd: 3,
    vibeTags: ["wabisabi", "neutraltones", "cozybooths"],
    description: "A peaceful slice of heaven tucked away in a quiet Hanoi alley. Filled with the warm aroma of cedarwood, soft rustling leaves, and gentle sunrays.",
    location: "Do Quang Alley • Trung Hoa • Hanoi",
    lighting: "Early Morning Light Filtering Through Wooden Windows",
    noise: "Rustic Acoustic Folk Tracks & Soft Alley Whispers",
    seating: "Raw Wooden Stools & Low Bamboo Desks",
    instagramHandle: "yencafe_hanoi",
    coVibersCount: 15,
    savedCount: 520,
    rating: "98% Quietude",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Classic Hanoi Egg Coffee", "Cold-Brewed White Lotus Jasmine Tea"],
    placeLayout: "A rustic wooden cabin nestled in an ancient brick courtyard beneath leafy shade",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Secret Courtyard (18k bookmarks)",
    lat: 21.0112,
    lng: 105.8016,
    explorerMode: "local"
  },
  {
    id: "spot-hanoi-2",
    name: "Thao Thu Garden • Hoan Kiem",
    category: "French Colonial Glass Atrium",
    city: "Hanoi",
    priceLevel: "$$",
    priceUsd: 8,
    vibeTags: ["plantparadise", "sagegreen", "wabisabi"],
    description: "A charming French colonial estate wrapping around a soaring botanical lightwell, offering gentle breezes in the heart of historic Hanoi.",
    location: "Ngo Quyen St • Ly Thai To • Hanoi",
    lighting: "Kaleidoscope Glass Skylight Under Golden Hour Sun",
    noise: "Soft Water Fountain Ripples & Stone Acoustics",
    seating: "Wrought-Iron French Garden Chairs & Teak Desks",
    instagramHandle: "thaothu_atrium",
    coVibersCount: 22,
    savedCount: 910,
    rating: "97% Timeless",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Artisanal Hibiscus Shaker Blend", "Wood-Fired Orange Butter Scone"],
    placeLayout: "A historic iron-framed conservatory draped in natural wild orchids",
    yelpRating: 4.7,
    googleRating: 4.8,
    instagramActivity: "Nostalgic Atrium (32k mentions)",
    lat: 21.0265,
    lng: 105.8568,
    explorerMode: "visitor"
  },
  {
    id: "spot-hanoi-3",
    name: "May Workspace • Ba Dinh",
    category: "Professional Creative workspace",
    city: "Hanoi",
    priceLevel: "$$",
    priceUsd: 6,
    vibeTags: ["minimalist", "cleanlines", "neutraltones"],
    description: "A premium, distraction-free coworking space designed for writers and creatives. Outfitted with high-speed fiber Wi-Fi, intelligent charging docks, and private study carrels.",
    location: "Phan Dinh Phung Blvd • Ba Dinh • Hanoi",
    lighting: "Comfortable 5000K Daylighting Spectrum",
    noise: "Absolute Silence & Gentle Pages Turning",
    seating: "Premium Ergonomic Office Chairs & Soft Leather Stools",
    instagramHandle: "may_workspace",
    coVibersCount: 8,
    savedCount: 410,
    rating: "99% Deep Focus",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Cold-Brew Orange Peel Blend", "Snow Lotus Lime Cooler"],
    placeLayout: "Glazed steel study nooks bordered by leafy bamboos and massive floor-to-ceiling bookshelves",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Elite Nomad Sanctum (12k mentions)",
    lat: 21.0401,
    lng: 105.8385,
    explorerMode: "work"
  },

  // --- BANGKOK ---
  {
    id: "spot-bangkok-1",
    name: "Sanrak Thonburi Tea",
    category: "Teakwood Canal Hideaway",
    city: "Bangkok",
    priceLevel: "$$",
    priceUsd: 7,
    vibeTags: ["wabisabi", "warmgoldenhour", "cozybooths"],
    description: "An ancient teak wood porch tucked away along the canals of Thonburi. Vintage earthen pottery, peaceful water ripples, and local floral infusions.",
    location: "Thonburi Riverside Lane • Bangkok",
    lighting: "Warm Amber Sunsets Shifting Over Canals",
    noise: "Whispering Waterfront Breeze & Windchim Tinkles",
    seating: "Low Cedar Mats & Bamboo Loungers",
    instagramHandle: "sanrak_tea",
    coVibersCount: 14,
    savedCount: 480,
    rating: "98% Secret Haven",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Saffron Hibiscus Iced Elixir", "Warm Taro Rice Mochi"],
    placeLayout: "Vintage tropical courtyard overlooking historical wooden boat locks",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Canal Magic (15k saved)",
    lat: 13.7367,
    lng: 100.4901,
    explorerMode: "local"
  },
  {
    id: "spot-bangkok-2",
    name: "Wat Pho Glass Pavilion",
    category: "Grand Heritage Conservatory",
    city: "Bangkok",
    priceLevel: "$$",
    priceUsd: 12,
    vibeTags: ["plantparadise", "sagegreen", "warmgoldenhour"],
    description: "A gorgeous soaring garden atrium adjacent to sacred stupas. Shimmering stained glass overlays casting kaleidoscope light over ancient frangipani leaves.",
    location: "Maha Rat Road • Phra Nakhon • Bangkok",
    lighting: "Glorious Golden Rays Reflecting Off Sacred Spire Glass",
    noise: "Muted Temple Bell Chimes & Gentle Breeze",
    seating: "Granite Plinths under Shaded Palm Arcs",
    instagramHandle: "watpho_pavilion",
    coVibersCount: 30,
    savedCount: 2200,
    rating: "99% Breath-taking Heritage",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Chilled Lemongrass Mint Tea", "Pandan Custard Steamed Brioche"],
    placeLayout: "High iron arches surrounding natural limestone pond with lotus blooms",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Iconic Masterwork (140k mentions)",
    lat: 13.7465,
    lng: 100.4930,
    explorerMode: "visitor"
  },
  {
    id: "spot-bangkok-3",
    name: "The Sukhumvit Focus Vault",
    category: "Professional Nomadic Labs",
    city: "Bangkok",
    priceLevel: "$$",
    priceUsd: 9,
    vibeTags: ["minimalist", "cleanlines", "brutalistmono"],
    description: "Designed for deep focus hours. Boasting individual work pods, hyper-fast fiber Wi-Fi, abundant charging outlets, and a strict no-loud-call rules zone.",
    location: "Sukhumvit Soi 21 • Khlong Toei • Bangkok",
    lighting: "Sleek Balanced Overhead LED and Adjustable Task Nodes",
    noise: "Soft Instrumental Synth Waves & Typing Patter",
    seating: "Ergonomic Mesh Task Chairs & Timber Bench Desks",
    instagramHandle: "focusvault_bkk",
    coVibersCount: 11,
    savedCount: 630,
    rating: "97% Productive Flow",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Concentrator Double Ristretto", "Matcha Sea Salt Energy Pods"],
    placeLayout: "Sleek industrial mezzanine with power strips, USB-C chargers, and focus zones",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Nomad Oasis (24k mentions)",
    lat: 13.7381,
    lng: 100.5612,
    explorerMode: "work"
  },

  // --- SINGAPORE ---
  {
    id: "spot-singapore-1",
    name: "The Booksmith Shophouse",
    category: "Cozy Heritage Book Corner",
    city: "Singapore",
    priceLevel: "$$$",
    priceUsd: 14,
    vibeTags: ["vintage", "wabisabi", "cozybooths"],
    description: "A stunning quiet haven nestled within a pastel-colored Tiong Bahru shophouse. Towering bookshelves, natural sunlight, and a rich smell of fresh paper.",
    location: "Yong Siak Street • Tiong Bahru • Singapore",
    lighting: "Subtle Warm Spotlights & Shaded Glass Skylight",
    noise: "Quiet Paper Flippings & Low Jazz Chords",
    seating: "Plush Velvet Armchairs & Warm Maple Desks",
    instagramHandle: "booksmith_sg",
    coVibersCount: 16,
    savedCount: 890,
    rating: "98% Literary Cozy",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Pandan Charcoal Latte", "Almond Croissant with Sea Salt Butter"],
    placeLayout: "Quaint narrow library room with historic green-tiled courtyard back patio",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Hidden Pearl (19k mentions)",
    lat: 1.2842,
    lng: 103.8306,
    explorerMode: "local"
  },
  {
    id: "spot-singapore-2",
    name: "Gardens Cloud Dome",
    category: "Futuristic Glass Conservatory",
    city: "Singapore",
    priceLevel: "$$$",
    priceUsd: 28,
    vibeTags: ["plantparadise", "sagegreen", "cleanlines"],
    description: "The ultimate tropical glass paradise. A soaring 35-meter indoor waterfall shrouded in mist, orchids, pitcher plants, and stunning skyways.",
    location: "Sprawling Marina Gardens Drive • Singapore",
    lighting: "Epic Glare of Giant Curvelinear Glass Truss Sky Dome",
    noise: "Rumbly Waterfall Spray & Echoing Bird Calls",
    seating: "Curved Slate Seats amongst dense jungle trails",
    instagramHandle: "clouddome_gardens",
    coVibersCount: 45,
    savedCount: 4800,
    rating: "99% Natural Masterwork",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Iced Passionfruit Pandan Shaker", "Cold Matcha Orchid Infusion"],
    placeLayout: "Monumental misty dome wrapping around a massive vertical garden mountain tower",
    yelpRating: 4.9,
    googleRating: 5.0,
    instagramActivity: "Global Wonder (510k mentions)",
    lat: 1.2841,
    lng: 103.8654,
    explorerMode: "visitor"
  },
  {
    id: "spot-singapore-3",
    name: "The Crane Work Club",
    category: "Creative Professional Sanctuary",
    city: "Singapore",
    priceLevel: "$$",
    priceUsd: 12,
    vibeTags: ["minimalist", "cleanlines", "neutraltones"],
    description: "An incredibly elegant workplace focusing on productivity. Spotlighting gorgeous shared desks, ergonomic standing setups, soundproof call booths, and bottomless workspace drinks.",
    location: "Kim Yam Road • River Valley • Singapore",
    lighting: "Warm Diffused Modern Workspace Sconces",
    noise: "Hushed Typing & Whisper Low Ambient Melodies",
    seating: "Steelcase Ergonomic Task Chairs & Oak Standing Desks",
    instagramHandle: "crane_workstudio",
    coVibersCount: 14,
    savedCount: 780,
    rating: "99% Focus Master",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Nitro Cold Brew with Vanilla Pod Cream", "Avocado Matcha Power Pot"],
    placeLayout: "Polished concrete loft with custom sound dampening dividers and green planter partitions",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Deep Focus Haven (16k mentions)",
    lat: 1.2936,
    lng: 103.8402,
    explorerMode: "work"
  },

  // --- ADDITIONAL WORK HIDEUOTS FOR POPULAR CITIES ---
  {
    id: "spot-hcmc-3",
    name: "Neo-Thao Dien Work Lab",
    category: "High-Speed Tech Coffee Space",
    city: "Ho Chi Minh City",
    priceLevel: "$$",
    priceUsd: 5,
    vibeTags: ["minimalist", "cleanlines", "neutraltones"],
    description: "A premium, high-tech coworking hub featuring a dedicated 1Gbps fiber internet connection, extra-wide kiln-dried white oak work desks, and infinite power outlets.",
    location: "Thao Dien Blvd • District 2 • HCMC",
    lighting: "Eye-Friendly 4500K Diffused Skylight Panel",
    noise: "Absolute Library Quiet (Headphones Highly Appreciated)",
    seating: "Genuine Herman Miller Aeron Chairs & Leather Cushions",
    instagramHandle: "thaodien_worklab",
    coVibersCount: 16,
    savedCount: 680,
    rating: "98% Hyper-Productive",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Lemongrass Citrus Cold Brew", "Flaky Double-Baked Matcha Croissant"],
    placeLayout: "A soundproofed air-conditioned workspace with separate single focus bays and integrated smart storage lockers",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Premium Work Sanctuary (15k bookmarks)",
    lat: 10.8038,
    lng: 106.7289,
    explorerMode: "work"
  },
  {
    id: "spot-tokyo-3",
    name: "Shibuya Terminal Hub & Study",
    category: "Tech Nomad Lab & Library",
    city: "Tokyo",
    priceLevel: "$$",
    priceUsd: 14,
    vibeTags: ["brutalistmono", "minimalist", "neutraltones"],
    description: "A super-sleek industrial high-fidelity workspace with soundproof micro call cabins, mechanical keyboards for guest rental, and unlimited specialty drip tea.",
    location: "Shibuya Crossing Lane • Tokyo",
    lighting: "Adjustable 4000K-6000K Desk Smart Glow Bars",
    noise: "Quiet Mechanical Keyboard Clacks & Low Lo-Fi Beats",
    seating: "Japanese Steelcase Task Chairs & Standing Timber Nodes",
    instagramHandle: "shibuya_terminal",
    coVibersCount: 18,
    savedCount: 910,
    rating: "99% Flow State achieved",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Matcha Espresso Duo Shaker", "Salted Butter Rice Crackers"],
    placeLayout: "Raw concrete double-vault with integrated multi-charger tables",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Nomad Oasis (42k mentions)",
    lat: 35.6580,
    lng: 139.7016,
    explorerMode: "work"
  },
  {
    id: "spot-ny-3",
    name: "The Archive Study",
    category: "West Village Work Sanctuary",
    city: "New York",
    priceLevel: "$$$",
    priceUsd: 18,
    vibeTags: ["vintage", "neutraltones", "cozybooths"],
    description: "An intellectual's dream. Brass study lamps, massive dark mahogany tables, high-speed fiber connection, and quiet policy strictly enforced by the curator.",
    location: "West 11th Street • Greenwich Village • New York",
    lighting: "Warm Concentrated Library Bulbs & Stained Windows",
    noise: "Silent Focus (Strictly Enforced No-Phone Rule)",
    seating: "Antique Green Leather Captain Chairs",
    instagramHandle: "thearchive_study",
    coVibersCount: 14,
    savedCount: 1200,
    rating: "98% Deep Intellectual Focus",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Siphon Blue Mountain Coffee", "Dark Chocolate Cranberry Loaf"],
    placeLayout: "Enclosed wooden study chamber lined with vintage literature and research shelves",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Quiet Mecca (34k mentions)",
    lat: 40.7358,
    lng: -74.0033,
    explorerMode: "work"
  },
  {
    id: "spot-sf-3",
    name: "SOMA Tech & Tea Vault",
    category: "High-Performance Work Cafe",
    city: "San Francisco",
    priceLevel: "$$",
    priceUsd: 15,
    vibeTags: ["minimalist", "cleanlines", "brutalistmono"],
    description: "Engineered for tech professionals. Features ergonomic standing desks, dedicated 5G wireless backup, silent focus cubicles and premium matcha taps.",
    location: "Howard Street • SOMA • San Francisco",
    lighting: "Daylight Balanced Bright Crisp Skylight Glow",
    noise: "Very Calm (Low keystrokes and hushed speech)",
    seating: "Herman Miller Embody Desks & Steel Stools",
    instagramHandle: "somatech_tea",
    coVibersCount: 22,
    savedCount: 1100,
    rating: "99% High Output Area",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Nitrogen Ceremonial Matcha Tap", "Avocado Rye Toast with microgreens"],
    placeLayout: "Open-space high truss industrial loft with custom sound absorber felt panels",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Trending Tech Hub (4k mentions)",
    lat: 37.7845,
    lng: -122.3985,
    explorerMode: "work"
  },

  // --- WORK PERSPECTIVE: FINE DINING & CLIENT MEETINGS ---
  {
    id: "spot-hanoi-client",
    name: "Tam Vi • Yen The (Client Meeting)",
    category: "Michelin Tea & Fine Dining House",
    city: "Hanoi",
    priceLevel: "$$$",
    priceUsd: 45,
    vibeTags: ["neutraltones", "wabisabi", "cozybooths"],
    description: "An exquisitely restored traditional ironwood mansion in the heart of Hanoi. Illuminated by soft nostalgic lamps with faint local acoustic strings, it is the perfect sanctuary for hosting high-profile clients and business dinners.",
    location: "Yen The St • Temple of Literature • Hanoi",
    lighting: "Vintage Brass Lanterns & Candlelight Dim",
    noise: "Elegant quietude, perfect for negotiations",
    seating: "Classic Rosewood Dining Chairs & Semi-Private Alcoves",
    instagramHandle: "tamvi_hanoi",
    coVibersCount: 12,
    savedCount: 1540,
    rating: "99% Elite",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Hand-Rolled River Prawn Rolls", "Claypot Herbal Caramelized Pork"],
    placeLayout: "Private glass dining room with bamboo screens and silk draperies",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Michelin Starred (28k mentions)",
    lat: 21.0261,
    lng: 105.8398,
    explorerMode: "work"
  },
  {
    id: "spot-bangkok-client",
    name: "The Saffron Heritage Lounge",
    category: "Chao Phraya Luxury Meeting Sanctuary",
    city: "Bangkok",
    priceLevel: "$$$$",
    priceUsd: 75,
    vibeTags: ["warmgoldenhour", "cozybooths", "sagegreen"],
    description: "Stunning upscale riverfront glass chambers overlooking Wat Arun. Spotlighting low warm spotlights, state-of-the-art acoustic muting, and signature Royal Thai fine dining perfect for high-profile business meetings.",
    location: "Charoen Krung Road • Phra Nakhon • Bangkok",
    lighting: "Sunset Amber Shimmer on Chao Phraya River",
    noise: "Ultra-low muffled river ambiance & gentle rhapsodies",
    seating: "Plush Velvet Private Curved Booths & Teak Executive Seats",
    instagramHandle: "saffron_lounge_bkk",
    coVibersCount: 16,
    savedCount: 1120,
    rating: "98% Majestic Dining",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Caviar Lemongrass Consommé", "Charred River Prawn with Sweet Tamarind Flambé"],
    placeLayout: "Stunning floor-to-ceiling glass pavilions hovering directly over the riverbank",
    yelpRating: 4.9,
    googleRating: 4.9,
    instagramActivity: "Sophisticated Gathering (35k mentions)",
    lat: 13.7242,
    lng: 100.5131,
    explorerMode: "work"
  },
  {
    id: "spot-singapore-client",
    name: "The Brass Atrium • Dempsey Hill",
    category: "Upscale Botanist Client Dining",
    city: "Singapore",
    priceLevel: "$$$",
    priceUsd: 55,
    vibeTags: ["plantparadise", "cleanlines", "sagegreen"],
    description: "A luxurious, foliage-engulfed botanical conservatory nestled inside Dempsey Hill. Perfect for elite power lunches and client pitches requiring quiet, lush, air-conditioned privacy.",
    location: "Dempsey Road • Tanglin • Singapore",
    lighting: "Diffused Glass Atrium Morning Glow & Warm Brass Sconces",
    noise: "Sophisticated soft buzz of high-profile conversations",
    seating: "Comfortable Green Leather Banquettes & Custom Rattan Chairs",
    instagramHandle: "brassatrium_sg",
    coVibersCount: 20,
    savedCount: 1420,
    rating: "97% Elite Power Lunch",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Barramundi Tarator with Herb oils", "Truffle Ricotta Brioche Toast"],
    placeLayout: "Glass dome dining lounge framed by massive preserved tree ferns and orchids",
    yelpRating: 4.8,
    googleRating: 4.8,
    instagramActivity: "Corporate Escape (15k mentions)",
    lat: 1.3045,
    lng: 103.8055,
    explorerMode: "work"
  },
  {
    id: "spot-hcmc-client",
    name: "An’s Garden Solarium • Thao Dien",
    category: "Elite Botanical Glass Mansion",
    city: "Ho Chi Minh City",
    priceLevel: "$$$",
    priceUsd: 38,
    vibeTags: ["plantparadise", "cleanlines", "sagegreen"],
    description: "A magnificent glass mansion hidden within Thao Dien's lush tropical gardens. Accented with brass fixtures and private soundproof meeting rooms, perfect for deal-making and business lunches.",
    location: "Thao Dien Blvd • District 2 • HCMC",
    lighting: "Golden Afternoon Sun Rays Softly Screened by Hanging Orchids",
    noise: "Serene Quietude & Isolated Business Comfort",
    seating: "Plush Turkey-Imported Genuine Leather Sofas",
    instagramHandle: "ans_garden_solarium",
    coVibersCount: 15,
    savedCount: 1850,
    rating: "98% Ultra-Premium",
    image: "https://images.unsplash.com/photo-1581349485608-9469926a8e5e?auto=format&fit=crop&q=80&w=600",
    menuHighlights: ["Elite Ginseng Abalone Soup", "Himalayan Salt-Stone Wagyu Ribeye"],
    placeLayout: "Double-height glass solarium with ample daylight and an surrounding outdoor koi pond",
    yelpRating: 4.8,
    googleRating: 4.9,
    instagramActivity: "Elite Client Hideaway (12k mentions)",
    lat: 10.8015,
    lng: 106.7262,
    explorerMode: "work"
  }
];
